name: CloudHub 2.0 Deployment
on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ID: ${{ secrets.CONNECTED_APP_CLIENTID }}
      SECRET: ${{ secrets.CONNECTED_APP_CLIENTSECRETS }}
      
    steps:
    - name: checkout code repo
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven
        
  upload:
    needs: build
    runs-on: ubuntu-latest
    env:
      ID: ${{ secrets.CONNECTED_APP_CLIENTID }}
      SECRET: ${{ secrets.CONNECTED_APP_CLIENTSECRETS }}
    
    steps:    
    
    - uses: actions/checkout@v3
    
    - name: Publish to Exchange 
      run: mvn deploy 
         -Dclient.id=$ID 
         -Dclient.secret=$SECRET  
         --file pom.xml -s .maven/settings.xml
         
       
  deploy:
    needs: upload
    runs-on: ubuntu-latest
    env:
      ID: ${{ secrets.CONNECTED_APP_CLIENTID }}
      SECRET: ${{ secrets.CONNECTED_APP_CLIENTSECRETS }}
    
    steps:    
    
    - uses: actions/checkout@v3
   
    - name: Deploy to CloudHub 2.0
      run: |
        mvn deploy -DmuleDeploy 
         -Dclient.id=$ID 
         -Dclient.secret=$SECRET --file pom.xml -s .maven/settings.xml
         
