name: CloudHub Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code repo
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build And Deploy to CloudHub
      env:
        CLIENTID: ${{secrets.CONNECTED_APP_CLIENTID}}
        CLIENTSECRET: ${{secrets.CONNECTED_APP_CLIENTSECRETS}}
        MULE_VERSION: ${{secrets.MULE_VERSION}}
        MULE_ENV: ${{secrets.MULE_ENV}}
      run: mvn clean deploy -DmuleDeploy -DmuleVersion=$MULE_VERSION -Denv=$MULE_ENV -Dclient.id=$CLIENTID -Dclient.secret=$CLIENTSECRET --file pom.xml  
