name: CloudHub Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code repo
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build And Deploy to CloudHub
      env:
        CONNECTED_APP_CLIENTID: ${{secrets.CONNECTED_APP_CLIENTID}}
        CONNECTED_APP_CLIENTSECRETS: ${{secrets.CONNECTED_APP_CLIENTSECRETS}}
        MULE_VERSION: ${{secrets.MULE_VERSION}}
        
      run: mvn clean deploy -DmuleDeploy \
          -Dmule.Version=$MULE_VERSION \
          -Dclient.id=$CONNECTED_APP_CLIENTID \
          -Dclient.secret=$CONNECTED_APP_CLIENTSECRETS --file=pom.xml
